// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyfslevizigxdydnhszz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZnNsZXZpemlneGR5ZG5oc3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzIyNDUsImV4cCI6MjA2ODk0ODI0NX0._601trqz73YkA6FEBWhjIxwEs5yHAPkkzdU3EAYAss0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});